[[redirects]]
from = "/"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/oss"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/timeplus"
to = "/install_timeplus.sh"
status = 200

[[redirects]]
from = "/sp-demo"
to = "/sp-demo.sh"
status = 200

[[redirects]]
from = "/latest-linux-amd64"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.1.6.2-linux-amd64.tar.gz"
status = 301
