[[redirects]]
from = "/oss"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/"
to = "/install_stable.sh"
status = 200

[[redirects]]
from = "/timeplus"
to = "/install_stable.sh"
status = 200

[[redirects]]
from = "/stable"
to = "/install_stable.sh"
status = 200

[[redirects]]
from = "/latest"
to = "/install_timeplus.sh"
status = 200

[[redirects]]
from = "/sp-demo"
to = "/sp-demo.sh"
status = 200

# 4 packages for stable builds

[[redirects]]
from = "/stable-linux-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.0-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/stable-linux-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.0-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/stable-darwin-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.0-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/stable-darwin-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.0-darwin-arm64.tar.gz"
status = 301

# 4 packages for latest builds (not so stable)

[[redirects]]
from = "/latest-linux-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.5-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-linux-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.5-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.5-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.3.5-darwin-arm64.tar.gz"
status = 301
