[[redirects]]
from = "/oss"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/"
to = "/stable"
status = 301

[[redirects]]
from = "/timeplus"
to = "/stable"
status = 301

[[redirects]]
from = "/stable"
to = "/install_2.4.sh"
status = 200

[[redirects]]
from = "/2.3"
to = "/install_2.3.sh"
status = 200

[[redirects]]
from = "/2.4"
to = "/install_2.4.sh"
status = 200

[[redirects]]
from = "/latest"
to = "/install_timeplus.sh"
status = 200

[[redirects]]
from = "/sp-demo"
to = "/sp-demo.sh"
status = 200

# 4 packages for latest builds (not so stable). We will change latest builds to RC.

[[redirects]]
from = "/latest-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.3 builds

[[redirects]]
from = "/2.3-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.3.5-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.3-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.3.5-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.3-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.3.5-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.3-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.3.5-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.4 builds

[[redirects]]
from = "/2.4-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.23-darwin-arm64.tar.gz"
status = 301
