[[redirects]]
from = "/"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/oss"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/timeplus"
to = "/install_timeplus.sh"
status = 200

[[redirects]]
from = "/stable"
to = "/install_stable.sh"
status = 200

[[redirects]]
from = "/sp-demo"
to = "/sp-demo.sh"
status = 200

[[redirects]]
from = "/stable-linux-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.0.43.2-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-linux-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.1.10.dev-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-linux-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.1.8.9-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-amd64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.1.8.9-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/latest-darwin-arm64.tar.gz"
to = "https://timeplus.io/dist/timeplus_enterprise/timeplus-enterprise-v2.1.8.9-darwin-arm64.tar.gz"
status = 301
