[[redirects]]
from = "/oss"
to = "/install_oss.sh"
status = 200

[[redirects]]
from = "/"
to = "/install_2.7.sh"
status = 200

[[redirects]]
from = "/timeplus"
to = "/install_2.7.sh"
status = 200

[[redirects]]
from = "/stable"
to = "/install_2.7.sh"
status = 200

[[redirects]]
from = "/2.7"
to = "/install_2.7.sh"
status = 200

[[redirects]]
from = "/2.6"
to = "/install_2.6.sh"
status = 200

[[redirects]]
from = "/2.5"
to = "/install_2.5.sh"
status = 200

[[redirects]]
from = "/2.4"
to = "/install_2.4.sh"
status = 200

[[redirects]]
from = "/preview"
to = "/install_preview.sh"
status = 200

[[redirects]]
from = "/sp-demo"
to = "/sp-demo.sh"
status = 200


# 4 packages for stable builds. Links on https://www.timeplus.com/install

[[redirects]]
from = "/stable-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/stable-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/stable-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/stable-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-darwin-arm64.tar.gz"
status = 301

# 4 packages for tech preview builds (not so stable)

[[redirects]]
from = "/preview-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.8.0-rc.1-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/preview-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.8.0-rc.1-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/preview-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.8.0-rc.1-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/preview-darwin-arm64.tar.gz"
# special case, rc1 doesn't include darwin-arm64
to = "https://d.timeplus.com/timeplus-enterprise-v2.8.0-rc.0-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.7 builds

[[redirects]]
from = "/2.7-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.7-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.7-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.7-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.7.2-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.6 builds

[[redirects]]
from = "/2.6-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.6.5-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.6-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.6.5-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.6-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.6.5-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.6-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.6.5-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.5 builds

[[redirects]]
from = "/2.5-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.5.12-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.5-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.5.12-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.5-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.5.12-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.5-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.5.12-darwin-arm64.tar.gz"
status = 301

# 4 packages for 2.4 builds

[[redirects]]
from = "/2.4-linux-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.26-linux-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-linux-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.26-linux-arm64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-darwin-amd64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.26-darwin-amd64.tar.gz"
status = 301

[[redirects]]
from = "/2.4-darwin-arm64.tar.gz"
to = "https://d.timeplus.com/timeplus-enterprise-v2.4.26-darwin-arm64.tar.gz"
status = 301

[[redirects]]
from = "/iceberg_preview1/timeplusd"
to = "https://timeplus.io/downloads/tpiceberg/timeplusd"
status = 301

[[redirects]]
from = "/iceberg_preview2/timeplusd"
to = "https://timeplus.io/downloads/iceberg20250320/timeplusd"
status = 301
